name: Run Gradle on PRs

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin

      - name: Run lint check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktfmtCheck

      - name: Run test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: test-results
          path: '**/build/test-results/test/TEST-*.xml'
          reporter: java-junit
